# Generated by Django 5.0 on 2024-01-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('source', models.URLField(max_length=500)),
                ('category', models.CharField(blank=True, choices=[('1', 'Machine Learning'), ('2', 'Economics'), ('3', 'Geopolitics'), ('4', 'Game Development'), ('5', 'Startups')], max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
        ),
    ]
