# Generated by Django 5.0 on 2024-01-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
